spring.application.name=event_board
spring.datasource.url=jdbc:postgresql://localhost:5432/events_board
spring.datasource.username=postgres
spring.datasource.password=3141
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret.access=48h0vjwEFH9YYWVNjtnakskOCbWUgIZ3kUDwhhGTbNA=
jwt.secret.refresh=yw6UM90hx/iiy9rE2fpYL6PUc9C6aZGzmoqaniAtAZA=

telegram.bot.username=partner_events_bot
telegram.bot.token=8191073087:AAH1Jg3RG0pis84tvTv7eP_rLbjEJESqlh0